Add security_group attribute to DB instance/clusters
vk-cs/terraform-provider-vkcs pull request #125
Opened 2023-04-02 00:22 UTC by ftersin

2023-04-03 21:22 UTC, paaanic commented on vkcs/db_shared.go
> +	if len(rawNetworks) > 1 {
Maybe, <= 1 supposed to be here?

2023-04-03 21:26 UTC, ftersin commented on vkcs/db_shared.go
> +	if len(rawNetworks) > 1 {
yep

2023-04-05 16:06 UTC, paaanic requested changes

2023-04-05 16:06 UTC, paaanic commented on CHANGELOG.md
> +- Add security_group argument to DB instance/cluster resources
Rebase is needed, this change goes into version 0.2.0

2023-04-05 16:06 UTC, paaanic commented on vkcs/resource_vkcs_db_cluster.go
> +							Description: "An array of one or more security group IDs to associate with the cluster instances. Changing this creates a new cluster. **New since v.0.1.16**.",
New since v.0.2.0

2023-04-05 16:06 UTC, paaanic commented on vkcs/resource_vkcs_db_cluster_with_shards.go
> +										Description: "An array of one or more security group IDs to associate with the shard instances. Changing this creates a new cluster. **New since v.0.1.16**.",
New since v.0.2.0

2023-04-05 16:06 UTC, paaanic commented on vkcs/resource_vkcs_db_instance.go
> +							Description: "An array of one or more security group IDs to associate with the instance. Changing this creates a new instance. **New since v.0.1.16**.",
New since v.0.2.0

2023-04-06 06:14 UTC, ftersin commented on examples/vkcs_db_cluster_with_shards/main.tf
> +    vkcs_networking_router_interface.db
indeed, dependency on secgroup is required, but not on the rule. Because changing of secgroup rule set are automatically propagated to existing ports

2023-04-06 07:22 UTC, merged