Add validation for vkcs_compute_instance.block_device.boot_index
vk-cs/terraform-provider-vkcs pull request #131
Opened 2023-04-04 13:30 UTC by paaanic

* Set `boot_index` default value to `-1`
* Validate that user set `boot_index` to `0` if more than one `block_device` is defined
* Set `boot_index` to `0` if only one `block_device` is defined

CMPT-28985

2023-04-04 15:42 UTC, ftersin requested changes
lets add a unit test for the logic

2023-04-06 06:58 UTC, ftersin requested changes
lets modify examples

2023-05-12 04:22 UTC, ftersin commented on vkcs/resource_vkcs_compute_instance_test.go
> +    boot_index = 0
not correct

2023-05-12 04:28 UTC, ftersin commented
> lets add a unit test for the logic

you changed all acceptance tests, but in a result we do not have tests w/ specified boot indexes in old manner
also we still do not have a test checking the logic (e.g. omitted boot index on secondary devices is converted to -1, not 1,2 etc)

2023-05-18 15:53 UTC, paaanic commented
> > lets add a unit test for the logic
> 
> you changed all acceptance tests, but in a result we do not have tests w/ specified boot indexes in old manner also we still do not have a test checking the logic (e.g. omitted boot index on secondary devices is converted to -1, not 1,2 etc)

Updated.

2023-05-18 15:53 UTC, paaanic commented on vkcs/resource_vkcs_compute_instance_test.go
> +    boot_index = 0
Removed.

2023-05-19 05:22 UTC, ftersin approved these changes

2023-05-19 10:46 UTC, merged