Add "skip_deletion" option for vkcs_db_user
vk-cs/terraform-provider-vkcs pull request #337
Opened 2023-11-22 08:28 UTC by paaanic

Allow user to skip deletion of Databases user, this is useful when deleting PostgreSQL users that own some database objects and therefore cannot be dropped.

CMPT-33820

2023-11-22 10:31 UTC, schirevko requested changes

2023-11-22 10:31 UTC, schirevko commented on vkcs/db/resource_user.go
> +							Description: "Boolean to control whether to user deletion should be skipped. If set to true, the resource will be removed from sthe tate, but the remote object will not be deleted. This is use
typo in "from sthe tate"

2023-11-22 10:33 UTC, ftersin commented on vkcs/db/resource_user.go
> +			skipDeletion = true
why do not exit here?

2023-11-23 09:23 UTC, paaanic commented on vkcs/db/resource_user.go
> +							Description: "Boolean to control whether to user deletion should be skipped. If set to true, the resource will be removed from sthe tate, but the remote object will not be deleted. This is use
Fixed.

2023-11-23 09:23 UTC, paaanic commented on vkcs/db/resource_user.go
> +			skipDeletion = true
Updated.

2023-11-23 10:53 UTC, ftersin approved these changes

2023-11-24 09:15 UTC, schirevko approved these changes

2023-11-24 09:54 UTC, merged