Add dns_domain and max_node_unavailable default values
vk-cs/terraform-provider-vkcs pull request #39
Opened 2022-07-05 14:02 UTC by qynonyq

2022-07-06 12:00 UTC, schirevko requested changes
Please, update example according to readme: https://github.com/vk-cs/terraform-provider-vkcs/blob/master/examples/README.md
There is new naming for examples, e.g example for creating cluster should be named as "vkcs-kubernetes-cluster-create": https://github.com/vk-cs/terraform-provider-vkcs/tree/master/examples/vkcs-kubernetes-cluster-create
This will enable canary test system to automatically run examples and ensure that they are working.

2022-07-08 09:44 UTC, qynonyq commented on examples/vkcs-kubernetes-cluster-create/provider.tf
> +}
removed

2022-07-08 09:44 UTC, qynonyq commented on examples/vkcs-kubernetes-node-group-create/base.tf
> +  }
removed

2022-07-08 09:44 UTC, qynonyq commented on examples/vkcs-kubernetes-node-group-create/main.tf
> +    cluster_id = "your_cluster_id"
fixed

2022-07-08 10:20 UTC, schirevko approved these changes

2022-07-08 10:42 UTC, merged