Vpn tunnel guide
vk-cs/terraform-provider-vkcs pull request #446
Opened 2024-05-31 08:51 UTC by morozovalekseywot

2024-06-07 05:38 UTC, ftersin commented on examples/vpnaas/base-image.tf
>    most_recent = true
we do not need most_recent with default

2024-06-07 05:41 UTC, ftersin commented on templates/vpnaas/guides/vkcs_vpn_tunnel.md.tmpl
> +  VPN Tunnel between Sprut network and Neutron network within VKCS.
VPN Tunnel to local network?

2024-06-07 05:43 UTC, ftersin commented on templates/vpnaas/guides/vkcs_vpn_tunnel.md.tmpl
> +A VPN tunnel is a network connection for securely transmitting information between two or more remote nodes on the Internet.
see https://cloud.vk.com/docs/en/networks/vnet/concepts/vpn

2024-06-11 09:16 UTC, morozovalekseywot commented on examples/vpnaas/base-image.tf
>    most_recent = true
done

2024-06-11 09:17 UTC, morozovalekseywot commented on templates/vpnaas/guides/vkcs_vpn_tunnel.md.tmpl
> +  VPN Tunnel between Sprut network and Neutron network within VKCS.
Can you explain what you want?

2024-06-26 09:07 UTC, schirevko requested changes

2024-06-26 09:07 UTC, schirevko commented on templates/vpnaas/guides/vkcs_vpn_tunnel.md.tmpl
> +You need both SDNs are enabled in your project to try the example.
> are enabled

without "are"

2024-06-26 09:46 UTC, ftersin commented on templates/vpnaas/guides/vkcs_vpn_tunnel.md.tmpl
> +You need both SDNs are enabled in your project to try the example.
done

2024-06-26 09:47 UTC, ftersin commented on templates/vpnaas/guides/vkcs_vpn_tunnel.md.tmpl
> +Neutron VPNaaS can plug several subnets to one VPN tunnel but a way it is used for that could be not supported by ceratin client VPN hardware.
done

2024-06-26 09:47 UTC, ftersin commented on templates/vpnaas/guides/vkcs_vpn_tunnel.md.tmpl
> +See `examples/vpnaas/neutron_vm.tf`, `examples/vpnaas/sprut_vm.tf` if you are interesting in.
done

2024-06-26 09:54 UTC, schirevko approved these changes

2024-06-26 10:32 UTC, merged